class TypeMismatchError(Exception): ...

class DuplicateValueError(Exception): ...

class MutuallyExclusiveError(Exception): ...

class NoTransactionError(Exception): ...

class NotInATransactionError(Exception): ...

class TableAlreadyExistsError(Exception): ...

class InATransactionError(Exception): ...

class InvalidOperationType(Exception): ...


